import { LegoBlockData, PricingKit, TestimonialItem } from "./types";

export const LEGO_BLOCKS: LegoBlockData[] = [
  {
    id: "focus",
    name: "Focus Block",
    category: "focus",
    color: "lego-yellow",
    colorHex: "#FFD000",
    accentHex: "#FFE44D",
    shadowHex: "#C99700",
    duration: "90 Mins",
    tagline: "One block. One priority. Zero screen noise.",
    description: "The hero block of your day. Built with a solid weighted core to ground your single most critical cognitively demanding task before noon.",
    cognitiveBenefit: "Reduces task-switching penalty by 68% via visual spatial commitment.",
    dimensions: "64 × 32 × 18 mm",
    weight: "58g weighted solid core",
    material: "Bead-blasted recycled ABS + Neodymium N52 magnetic anchor",
    iconName: "Zap",
    studs: 4,
  },
  {
    id: "work",
    name: "Deep Work Block",
    category: "work",
    color: "lego-blue",
    colorHex: "#0055BF",
    accentHex: "#2E7DF6",
    shadowHex: "#003E8C",
    duration: "60 Mins",
    tagline: "Uninterrupted engineering & deep problem solving.",
    description: "Designed for shipping code, drafting architecture, writing strategy docs, or deep analytical workflows without notifications.",
    cognitiveBenefit: "Locks working memory onto one track, eliminating attention residue.",
    dimensions: "64 × 32 × 18 mm",
    weight: "58g weighted solid core",
    material: "Matte-finish precision molded polymer",
    iconName: "Cpu",
    studs: 4,
  },
  {
    id: "health",
    name: "Health & Reset Block",
    category: "health",
    color: "lego-green",
    colorHex: "#00853D",
    accentHex: "#1BB85E",
    shadowHex: "#00602B",
    duration: "45 Mins",
    tagline: "Because high output requires deliberate restoration.",
    description: "Physical reminder for hydration, 10k steps, gym sessions, outdoor sunlight, or nervous system regulation.",
    cognitiveBenefit: "Prevents dopamine depletion and mid-afternoon energy crashes.",
    dimensions: "48 × 32 × 18 mm",
    weight: "44g weighted solid core",
    material: "Satin botanical green polymer",
    iconName: "HeartPulse",
    studs: 3,
  },
  {
    id: "break",
    name: "Buffer & Break Block",
    category: "break",
    color: "lego-red",
    colorHex: "#E3000B",
    accentHex: "#FF4D57",
    shadowHex: "#B80009",
    duration: "20 Mins",
    tagline: "Productivity isn't working forever. It's rhythmic recovery.",
    description: "Snaps between heavy focus sessions. Forces you to step away from your monitor, breathe, stretch, and let ideas incubate unconsciously.",
    cognitiveBenefit: "Activates default mode network for subconscious creative breakthrough.",
    dimensions: "32 × 32 × 18 mm",
    weight: "36g weighted solid core",
    material: "Classic iconic LEGO crimson ABS",
    iconName: "Coffee",
    studs: 2,
  },
  {
    id: "goal",
    name: "North Star Block",
    category: "goal",
    color: "lego-purple",
    colorHex: "#7C3AED",
    accentHex: "#A78BFA",
    shadowHex: "#5B21B6",
    duration: "Weekly / All Day",
    tagline: "The one needle-mover that defines success.",
    description: "The elevated crown block resting on top of your daily stack. If this single thing happens today, your day was an undeniable win.",
    cognitiveBenefit: "Eliminates the Zeigarnik effect by creating binary clarity on victory.",
    dimensions: "32 × 32 × 24 mm (Crown Height)",
    weight: "48g CNC brass interior core",
    material: "Metallic-infused violet polymer with laser etched star stud",
    iconName: "Target",
    studs: 2,
  },
  {
    id: "admin",
    name: "Async Comms Block",
    category: "admin",
    color: "lego-orange",
    colorHex: "#FF6200",
    accentHex: "#FF8C42",
    shadowHex: "#CC4E00",
    duration: "30 Mins",
    tagline: "Batch all messages, emails, and syncs into one tight box.",
    description: "Quarantine Slack, email triage, PR reviews, and team syncs into a dedicated physical block instead of letting them bleed all day.",
    cognitiveBenefit: "Protects deep focus hours from death-by-a-thousand-pings.",
    dimensions: "32 × 32 × 18 mm",
    weight: "36g weighted solid core",
    material: "High-visibility warning orange polymer",
    iconName: "Inbox",
    studs: 2,
  },
];

export const PRICING_KITS: PricingKit[] = [
  {
    id: "starter",
    name: "LifeBlocks™ Starter Kit",
    subtitle: "The essential tactile daily ritual for individuals and students.",
    popular: false,
    priceINR: 2499,
    originalPriceINR: 3499,
    priceUSD: 29,
    originalPriceUSD: 42,
    description: "Everything you need to replace messy digital to-do lists with a clean, focused, 3-block daily desk stack.",
    includes: [
      "8× Precision Weighted LifeBlocks",
      "1× Anodized Desk Baseplate (Matte Bone)",
      "1× Daily Morning Stacking Guide",
      "1× Magnetic Dry-Erase Goal Tile",
      "Recycled Paper Craft Travel Box",
    ],
    blockCount: 8,
    baseplateType: "Single Row Desk Base (240mm)",
    features: [
      "2× Focus Blocks (90m)",
      "2× Deep Work Blocks (60m)",
      "2× Break & Buffer Blocks (20m)",
      "1× Health & Reset Block (45m)",
      "1× North Star Crown Block",
      "Free India & Global Tracked Shipping",
      "30-Day Tactile Satisfaction Guarantee",
    ],
    stockCount: 14,
  },
  {
    id: "creator-pro",
    name: "LifeBlocks™ Creator Pro",
    subtitle: "The definitive setup for engineers, designers, founders & creators.",
    badge: "MOST POPULAR",
    popular: true,
    priceINR: 4499,
    originalPriceINR: 5999,
    priceUSD: 54,
    originalPriceUSD: 75,
    description: "Full-day modular planning system with multi-track morning, afternoon, and evening baseplates plus the tactile Pomodoro mechanical slider.",
    includes: [
      "16× Precision Weighted LifeBlocks",
      "1× Dual-Track CNC Aluminum Baseplate (Slate/Gold)",
      "1× Analog Mechanical Pomodoro Slider Indicator",
      "2× North Star Goal Anchors",
      "4× Quick-Swap Micro Subtask Studs",
      "Premium Matte Hard-Shell Felt Storage Case",
    ],
    blockCount: 16,
    baseplateType: "Dual-Track Studio Base (360mm CNC Aluminum)",
    features: [
      "4× Focus Blocks (90m)",
      "4× Deep Work Blocks (60m)",
      "3× Break & Buffer Blocks (20m)",
      "2× Health & Reset Blocks (45m)",
      "2× Async Comms Blocks (30m)",
      "1× Obsidian North Star Goal Crown",
      "Free Priority Express Shipping",
      "Lifetime Magnetic Snap Warranty",
    ],
    stockCount: 9,
  },
  {
    id: "executive-studio",
    name: "LifeBlocks™ Executive Studio",
    subtitle: "Architect your entire week. The ultimate tangible productivity masterwork.",
    badge: "COLLECTOR EDITION",
    popular: false,
    priceINR: 7999,
    originalPriceINR: 10999,
    priceUSD: 99,
    originalPriceUSD: 135,
    description: "Weekly architectural matrix baseplate with 32 blocks, solid walnut wood & brushed brass accent trim, and custom laser-engraved nameplate.",
    includes: [
      "32× Master Collection LifeBlocks",
      "1× 7-Day Architectural Wall/Desk Modular Matrix",
      "1× Solid American Walnut Dock with Brass Stud Accents",
      "2× Analog Flow Timers with Magnetic Snap Base",
      "Custom Laser Engraving with Your Name or Mantra",
      "Numbered Certificate of Authenticity (Batch #01)",
    ],
    blockCount: 32,
    baseplateType: "7-Day Architectural Matrix (Solid Walnut + Anodized Aluminum)",
    features: [
      "Full spectrum 32-block suite across all 6 categories",
      "Dedicated Monday-to-Sunday weekly grid",
      "Custom Laser Engraving included",
      "White-Glove Courier Delivery in Wooden Case",
      "Direct consultation with LEGO Life Ergonomics Team",
    ],
    stockCount: 5,
  },
];

export const TESTIMONIALS: TestimonialItem[] = [
  {
    id: "aarav",
    name: "Aarav Sharma",
    role: "Senior Staff Engineer",
    company: "Bengaluru",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    rating: 5,
    quote: "I stopped opening Notion every five minutes just to check what I was supposed to do. Having three physical blocks sitting in front of my keyboard created an impenetrable mental wall against tab switching.",
    metric: "−3.5 hrs",
    metricLabel: "Daily screen distraction",
    setupType: "Creator Pro (Dual-Track)",
    verified: true,
  },
  {
    id: "meera",
    name: "Dr. Meera Nair",
    role: "Resident Physician & Neuro researcher",
    company: "AIIMS New Delhi",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    rating: 5,
    quote: "In neuroscience, we know spatial physical anchors trigger higher prefrontal cortex activation than glass screens. LifeBlocks is the first productivity tool that actually honors human brain mechanics.",
    metric: "94%",
    metricLabel: "Daily plan completion",
    setupType: "Starter Kit",
    verified: true,
  },
  {
    id: "dev",
    name: "Dev Patel",
    role: "Founder & YC Alum",
    company: "SaaS Studio",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    rating: 5,
    quote: "It sounds almost ridiculously simple: you pick 3 blocks in the morning, build the stack, and execute. That's exactly why it works. Every software to-do list suffers from infinite bloat; physical blocks enforce brutal prioritization.",
    metric: "4.8 hrs",
    metricLabel: "Average deep focus logged",
    setupType: "Executive Studio Kit",
    verified: true,
  },
  {
    id: "sophia",
    name: "Sophia Chen",
    role: "Principal Product Designer",
    company: "Design Systems Lab",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    rating: 5,
    quote: "The tactile feedback of snapping the yellow Focus block onto the CNC baseplate in the morning is the most satisfying ritual on my desk. It feels like real industrial design art.",
    metric: "100%",
    metricLabel: "Zero digital to-do app fatigue",
    setupType: "Creator Pro Kit",
    verified: true,
  },
];

export const FAQS = [
  {
    question: "Why should I use physical blocks when I already have Todoist, Notion, or Apple Reminders?",
    answer: "Digital to-do apps suffer from the 'Invisible Tab Dilemma': they live behind 40 browser tabs, get buried beneath Slack notifications, and allow infinite task list bloat. A physical LEGO LifeBlock sits directly beneath your monitor within your peripheral vision at all times. You cannot hide it, swipe it away, or overload it with 60 tasks. It forces ruthless, tangible focus on what actually moves the needle today.",
    category: "Philosophy",
  },
  {
    question: "How do the blocks connect and stay in place on my desk?",
    answer: "Every LifeBlock features precision-engineered interlocking studs combined with internal Neodymium N52 magnetic cores. They snap onto the anodized aluminum desk baseplate with a distinct, satisfying tactile click and remain rock-solid even if bumped.",
    category: "Hardware",
  },
  {
    question: "What happens if my schedule changes during the middle of the day?",
    answer: "That is the exact superpower of LifeBlocks: modularity. When an urgent priority emerges, you physically pick up a block, swap it for a Break or Comms block, and restack. The physical act of re-arranging blocks makes you consciously aware of the trade-off you are making.",
    category: "Usage",
  },
  {
    question: "What materials are LifeBlocks made from?",
    answer: "Blocks are precision injection molded from 100% recycled high-density matte ABS polymer with bead-blasted satin texture (resists fingerprints and oils), weighted with a CNC internal core for a premium 40-58g hand feel. Baseplates are crafted from aerospace-grade 6061 anodized aluminum with non-slip cork silicone feet.",
    category: "Hardware",
  },
  {
    question: "How long does shipping take, and what is the return policy?",
    answer: "We ship orders within 24-48 hours. Domestic delivery in India takes 2-4 business days. International express shipping takes 4-7 business days. We offer an unconditional 30-day tactile satisfaction guarantee: if you don't feel noticeably calmer and more focused, return it for a 100% full refund.",
    category: "Shipping",
  },
];
